/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  ArrowRight, Save, RotateCcw, Download, Sparkles, CheckCircle, 
  AlertTriangle, UploadCloud, FileText, Loader2, BookOpen, Trash2
} from "lucide-react";
import { defaultLectures } from "../data/defaultLectures";
import { SmartGuide } from "./SmartGuide";

interface ExerciseField {
  id: string;
  label: string;
  placeholder: string;
  guideTitle: string;
  guideDescription: string;
  guidePoints: string[];
  guideQuote?: string;
}

interface SectionViewProps {
  sectionId: string;
  answers: Record<string, string>;
  onSave: (sectionId: string, answers: Record<string, string>, silent?: boolean) => void;
  onReset: (sectionId: string, type: "all" | "local") => void;
  onBackToDashboard: () => void;
  onToast: (message: string, type: "success" | "info" | "error") => void;
  id?: string;
}

export const SectionView: React.FC<SectionViewProps> = ({
  sectionId,
  answers,
  onSave,
  onReset,
  onBackToDashboard,
  onToast,
  id
}) => {
  const [localAnswers, setLocalAnswers] = useState<Record<string, string>>({});
  const [showConfirmReset, setShowConfirmReset] = useState(false);
  const [resetType, setResetType] = useState<"all" | "local">("local");
  
  // Custom exercises generated by AI (loaded from localStorage if exists)
  const [exercises, setExercises] = useState<ExerciseField[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [transcriptText, setTranscriptText] = useState("");
  const [showUploadModal, setShowUploadModal] = useState(false);

  // Load section meta
  const defaultMeta = defaultLectures.find((sec) => sec.id === sectionId) || defaultLectures[0];
  const [sectionTitle, setSectionTitle] = useState(defaultMeta.title);
  const [sectionDesc, setSectionDesc] = useState(defaultMeta.description);

  // Initialize fields and default answers
  useEffect(() => {
    // Check if custom AI exercises exist for this section
    const savedCustom = localStorage.getItem(`custom_exercises_${sectionId}`);
    if (savedCustom) {
      try {
        const parsed = JSON.parse(savedCustom);
        setExercises(parsed.exercises || []);
        setSectionTitle(parsed.title || defaultMeta.title);
        setSectionDesc(parsed.description || defaultMeta.description);
      } catch {
        loadDefaults();
      }
    } else {
      loadDefaults();
    }
  }, [sectionId]);

  // Load baseline fields if no AI override
  const loadDefaults = () => {
    setSectionTitle(defaultMeta.title);
    setSectionDesc(defaultMeta.description);
    
    // Mapping static baseline exercises
    let baselineExercises: ExerciseField[] = [];
    if (sectionId === "competitors") {
      baselineExercises = [
        {
          id: "comp_classification",
          label: "تحديد وتصنيف منافسيك (نفس المنتج 100%، منتجات مشابهة 60-70%، وحلول نفس المشكلة):",
          placeholder: "مثال:\n1. منافس مباشر (100%): متجر 'س' يبيع نفس حزام الظهر ولديه حساب انستقرام نشط.\n2. منافس مشابه (70%): متجر 'ص' يبيع كرسي مريح لتقويم الظهر بخصم 15%.\n3. منافس لحل المشكلة: عيادة علاج طبيعي تقدم تمارين تقوية عضلات الظهر المنزلية...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "comp_discovery_methods",
          label: "طرق وقنوات العثور على المنافسين (Google Search, Facebook Library, TikTok, Amazon):",
          placeholder: "مثال:\n- الكلمات المفتاحية المستخدمة: 'ألم أسفل الظهر'، 'علاج تقوس الظهر'.\n- مكتبة إعلانات فيسبوك: وجدنا إعلان لمتجر 'س' يعمل منذ 45 يوماً (مما يدل على نجاحه).\n- أمازون: مراجعات العملاء السلبية تشتكي من جودة القماش ورائحة البلاستيك في أحزمة المنافسين...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "comp_store_analysis",
          label: "تحليل صفحات منتجات المنافسين (الرسائل، الصور والفيديوهات، السعر والعرض، الثقة والاستعجال):",
          placeholder: "مثال:\n- الرسائل: يركزون على 'التخلص من الألم فوراً' و'استعادة القوام الرياضي'.\n- الصور: يستخدمون صور 3D مجردة مأخوذة من علي إكسبريس.\n- العرض: سعر البيع 49$ مع شحن مجاني عند شراء حزامين (حزم Bundles).\n- الثقة والاستعجال: لديهم مؤقت تنازلي (عشر دقائق) ومراجعات نصية بدون صور حقيقية...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        },
        {
          id: "comp_ad_creatives",
          label: "تحليل إعلانات المنافسين (أشكال الإعلانات، الخطافات الأكثر تكراراً، والفرص والاعتراضات غير المجابة):",
          placeholder: "مثال:\n- أشكال الإعلانات: يعتمدون بشكل كامل على فيديوهات الـ UGC والمقارنة قبل وبعد.\n- الخطاف الأكثر تكراراً: 'هذا الشيء غير شكل ظهري وجعلني أكثر ثقة بين زملائي في العمل!'.\n- الفوائد المكررة: النتيجة السريعة وتخفيف الألم.\n- الفجوات/الاعتراضات: لا يشرحون هل الحزام مرن تحت البدلة الرسمية؟ وهل هو آمن للاستخدام أثناء القيادة؟...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        },
        {
          id: "comp_strategy_transition",
          label: "تحويل التحليل لاستراتيجيتك الخاصة (الجمهور، التموضع والوعد، العرض الخارق، 3 زوايا إعلانية، و5 تحسينات لمتجرك):",
          placeholder: "مثال:\n- الجمهور (Avatar): رجال موظفو مكاتب 30-50 عاماً يرتدون بدلات رسمية ويعانون من آلام الجلوس الطويل.\n- التموضع والوعد: شكل أنحف، وضعية صحية مستقيمة غير مرئية تحت الملابس.\n- العرض الخارق: اشتر حزام واحد واحصل على الثاني مجاناً + شحن مجاني فوري + ضمان ذهبي 30 يوماً للاسترجاع.\n- 3 زوايا إعلانية: (1) زاوية الراحة التامة بالمكتب، (2) زاوية قبل وبعد تحت البدلة، (3) زاوية الإجابة على اعتراض 'هل يظهر تحت الملابس؟'.\n- 5 تحسينات لمتجرنا: شرح آلية العمل بالرسم، صور لقطات Lifestyle حية لرجال ببدلات، مراجعات حقيقية بالصور والفيديو، صفحة أسئلة شائعة تجيب على كافة الاعتراضات، توضيح مدة الشحن الدقيقة...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "targetAudience") {
      baselineExercises = [
        {
          id: "audience_human_definition",
          label: "تعريف العميل كإنسان (تحديد من يواجه المشكلة وراء السن والجنس السطحي):",
          placeholder: "مثال:\n- المشكلة: ألم تقوس الظهر والرقبة بسبب الجلوس المكتبي الطويل لعدة ساعات متواصلة.\n- العميل كإنسان: أي موظف أو كاتب أو مبرمج يضطر للعمل خلف شاشة الكمبيوتر، ويشعر بالخمول أو تراجع المظهر الرياضي بسبب انحناء كتفيه للخارج، بغض النظر عن سنه أو جنسه كعامل حيد...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "pain_moment_scenario",
          label: "تحليل لحظة الوجع والسيناريو اليومي (الوجع، المشهد الزماني/المكاني، المشاعر السلبية، الأمنية):",
          placeholder: "مثال (منتج عناية بالبشرة):\n1. الوجع: احمرار وتهيج مفاجئ للبشرة.\n2. المشهد: أثناء التجهيز لمناسبة هامة بعد تجربة منتج تجميل رائج (ترند).\n3. المشاعر: قلق وإحباط وخوف من تلف البشرة الدائم.\n4. الأمنية: بشرة هادئة وصافية وصحية بأسرع وقت وبأمان تام...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "deep_research_dictionary",
          label: "قاموس كلمات ومصطلحات العميل الحقيقية (المستخرجة من المراجعات والمنصات):",
          placeholder: "مثال:\n- عبارات حرفية للعملاء من أمازون وتيك توك: 'كتوفي ذابت'، 'رقبتي متصلبة مثل الخشب'، 'أخجل ألبس قميص ضيق'، 'جربت كريمات كثيرة وحرقت وجهي'.\n- سنستخدم هذه العبارات الحرفية في صياغة الخطافات التسويقية لمتجرنا...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        },
        {
          id: "five_big_questions",
          label: "الأسئلة الخمسة الكبرى وتحليل سيكولوجية الشراء العاطفية والحلول البديلة:",
          placeholder: "مثال:\n1. الرغبة الكبرى: قوام مستقيم وثقة بالنفس دون جهد.\n2. المخاوف والألم: استمرار الألم ليصبح مزمناً وتشويه المظهر.\n3. الأحلام والأمنيات: التخلص من المشدات المزعجة والشعور بالراحة المكتملة.\n4. حلول جربوها سابقاً: مسكنات، تمارين تمدد عشوائية، مشدات رخيصة تسبب تعرقاً.\n5. سبب فشلها: عدم ثبات المفعول أو التسبب في تهيج والتهاب الجلد وسرعة تلفها العضوي العادي...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "marketingAngles") {
      baselineExercises = [
        {
          id: "features_vs_angles",
          label: "صياغة الميزة مقابل الزاوية التسويقية (تحويل مميزات منتجك الجافة إلى معانٍ وأثر نفسي يلامس العميل):",
          placeholder: "مثال:\n- الميزة (Feature): قماش المشد ناعم وقوي ومزود بثقوب تهوية متناهية الصغر.\n- الزاوية التسويقية (Angle): لن يلاحظ أحد على الإطلاق أنك ترتدي مشداً تحت بدلتك الرسمية، ولن تشعر أنت بوجوده بفضل النعومة وخفة الوزن الاستثنائية للنسيج طوال ساعات العمل...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "angle_sources_extraction",
          label: "استخراج الزوايا التسويقية من مصادرها الخمسة (الألم، الرغبة، الاعتراضات، الحلول الفاشلة السابقة، الهوية):",
          placeholder: "مثال (منتج آلام وقوام الظهر):\n1. زاوية ألم: 'ألم ظهرك يشتت تركيزك الذهني في العمل ويخرب يومك؟'.\n2. زاوية رغبة: 'تخيل أن تقف بظهر مستقيم تماماً وقوام يفيض بالثقة والرجولة'.\n3. زاوية اعتراض: 'مشدنا مصمم بمواد مضادة للروائح والتعرق ومرن جداً ليناسب الحركة اليومية الكثيفة'.\n4. زاوية حلول فاشلة: 'المسكنات والتمارين العشوائية تعطي راحة مؤقتة، تصميمنا يعيد توجيه فقرات الظهر تدريجياً لراحة مستدامة'.\n5. زاوية هوية: 'مخصص لرجال الأعمال والموظفين الطموحين الطامحين لقوام مستقيم يفرض الاحترام والجاذبية في كل قاعة اجتماعات'...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "seven_levels_depth",
          label: "تطبيق مستويات التعمق السبعة على زاويتك المفضلة (المشهد، الشعور، العدو، الآلية، الإثبات، العرض، الـ CTA):",
          placeholder: "مثال (منتج عناية بالبشرة):\n1. المشهد: احمرار وتهيج فظيع للوجه بعد 10 دقائق فقط من استخدام كريم ترند رخيص ومجهول.\n2. الشعور: الندم الشديد، الخوف من تلف البشرة الدائم، والإحراج من الخروج.\n3. العدو المشترك: المكونات الكيميائية القاسية والعطور المصنعة في كريمات الترندات العشوائية السريعة.\n4. الآلية الفريدة: كريمنا طبيعي 100% بمستخلصات مهدئة لإصلاح حاجز البشرة المتضرر فوراً بأمان مكمل.\n5. الإثبات: مئات التقييمات والصور لفتيات جربن عشرات الحلول وفشلت، وهدأت بشرتهن بالكامل معنا.\n6. العرض: احصلي على عبوة التهدئة الفورية بضمان ذهبي 30 يوماً للاسترجاع بلا شروط.\n7. الـ CTA: انقري هنا لتهدئة بشرتك الحساسة فوراً وبأمان كامل...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        },
        {
          id: "testing_scaling_strategy",
          label: "استراتيجية اختبار الزوايا التسويقية المبتدئة وصياغة خطافات (Hooks) مختلفة لكل زاوية:",
          placeholder: "مثال:\n- الزاوية التسويقية الكبرى: 'الراحة والإنتاجية العالية في المكتب دون تشتيت الألم'.\n- الخطاف الإعلاني 1 (Hook 1): 'لماذا تبدو كتوفك منحنية وتظهر بمظهر غير رياضي في صور الاجتماعات الهامة؟'.\n- الخطاف الإعلاني 2 (Hook 2): 'هذا الحزام السري لا أحد يراه تحت قميصك، ولكنه سيخلصك من آلام الجلوس الطويل المكتبي'.\n- خطة الاختبار: إطلاق حملة اختبار بميزانية متواضعة لاختبار أداء كلا الخطافين، وتتبع الإحصاءات لتطوير وتوسيع الزاوية الفائزة (Scaling)...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "messagePillars") {
      baselineExercises = [
        {
          id: "authority_trust",
          label: "صياغة الركائز الرسائلية الأساسية للبراند (من 3 إلى 5 رسائل ثابتة تحدد صورة البراند والتحول المطلوب):",
          placeholder: "مثال (براند مكملات غذائية مثل AG1):\n1. صحتك بدون تعقيد (الرسالة والوعد الكلي).\n2. التزام أسهل من أي روتين آخر (تسهيل وتثبيت العادة).\n3. راحة بال وأمان صحي (Scoop واحد يغطي كافة الأساسيات).\n4. خطوة يومية صغيرة لتغيير كبير (التكرار والاستمرارية).\n5. طاقة مستقرة ونشاط دائم (بدون توتر الكافيين)...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "speed_ease",
          label: "تحديد الفروق الجوهرية والوعود الثابتة مقابل مداخل وزوايا الإعلانات المقترحة لبراندك:",
          placeholder: "مثال:\n- الركيزة الثابتة: 'صحتك بدون تعقيد'.\n- الزاوية التسويقية 1: 'التعب والإرهاق من كثرة علب المكملات وتناول 10 حبوب يومياً'.\n- الزاوية التسويقية 2: 'روتين صباحي سريع للغاية لا يتعدى 30 ثانية لتنشيط يومك بالكامل'.\n- الزاوية التسويقية 3: 'الحد الأدنى الفعال لحماية مناعتك وتحسين هضمك'...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "risk_reversal",
          label: "خطة تفادي الأخطاء التسويقية الشائعة وبناء صورة ذهنية طويلة المدى لجمهورك:",
          placeholder: "مثال:\n- تفادي كثرة الرسائل: الالتزام بـ 4 رسائل واضحة فقط وعدم التشتت بفوائد تقنية دقيقة.\n- تجنب التركيز التقني: التركيز على 'التحول والشعور بالنشاط' بدلاً من الاكتفاء بسرد المكونات.\n- الاتساق والثبات: توحيد النبرة والأسلوب في كافة المنصات والمتجر لتبدو كبراند احترافي وموثوق ومستمر...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "contentFormats") {
      baselineExercises = [
        {
          id: "ugc_videos",
          label: "تخطيط إعلانات الفيديو القصير التفاعلي (UGC Video Ads):",
          placeholder: "تصوير عميل يتحدث عن شكه الأولي قبل التجربة، ثم إظهار وجهه المنبهر بالنتائج أثناء استخدام لوحة التحكم الخاصة بنا...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "carousel_graphics",
          label: "منشورات الكاروسيل الطويلة والشرائح التعليمية القيمة:",
          placeholder: "كاروسيل من 5 صفحات: 1. المشكلة الصادمة، 2. الخطأ الأول الشائع، 3. التحليل الفني، 4. خطوات التجنب، 5. الدعوة للشراء الفورية...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        },
        {
          id: "case_studies",
          label: "صياغة دراسات الحالة العميقة وشهادات العملاء الحية:",
          placeholder: "قصة 'خالد' تاجر العطور السلكي الذي كاد يغلق مشروعه، وكيف تضاعفت أرباحه 4 مرات في 20 يوماً باستخدام قمع مبيعاتنا الخاص...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "hooksScripts") {
      baselineExercises = [
        {
          id: "hooks_lines",
          label: "صياغة 3 خطافات إعلانية جذابة وخاطفة للانتباه (Scroll-Stoppers):",
          placeholder: "مثال:\n1. 'لماذا يفشل أغلب الناس في الالتزام بالفيتامينات؟' (هوك فضول)\n2. 'إذا كان ظهرك يؤلمك عند الجلوس الطويل، استمع لهذا..' (هوك مشكلة مباشرة)\n3. 'المشكلة ليست فيك، المشكلة في روتينك الصباحي!' (هوك صدمة ومفاجأة)...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "ad_script",
          label: "سيناريو الفيديو الإعلاني الكامل (المقدمة، المشكلة، الحل، والـ CTA):",
          placeholder: "مثال لسيناريو كامل:\n- [0:00-0:03] (الهوك): 'كم مرة اشتريت مكملات ونسيتها في الدرج؟'\n- [0:03-0:10] (الموقف والمسألة): مشهد لشخص يفتح درباً مليئاً بعلب الفيتامينات المغبرة.\n- [0:10-0:20] (تضخيم الألم): 'التعقيد هو العدو الذي يمنعك من الوصول لجسم مثالي ونشاط مستمر.'\n- [0:20-0:35] (الحل): 'منتجنا يجمع كل تلك الفوائد في Scoop واحد سريع يذوب بـ 30 ثانية.'\n- [0:35-0:45] (العرض والضمان): 'ضمان ذهبي 100% لاسترجاع الأموال مع شحن مجاني لأول 100 طلب.'\n- [0:45-0:50] (CTA): 'اضغط هنا واطلب باقتك الموفرة الآن'...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    } else if (sectionId === "adStrategy") {
      baselineExercises = [
        {
          id: "budget_allocation",
          label: "هيكلية خطة الإعلانات واستراتيجية المحتوى لحملتك (الجمهور، الزوايا، العرض، القالب):",
          placeholder: "مثال لتطبيق إطار العمل:\n1. الجمهور: المشغولات اللاتي يبحثن عن عادة صحية سهلة.\n2. الزاوية التسويقية: 'صحتك بدون تعقيد'.\n3. الرسالة المركزية: وعاء واحد يمنحك الطاقة اليومية دون الحاجة لعشرات علب الفيتامينات.\n4. آلية عمل الحل: تركيبة سريعة الذوبان تغطي كافة احتياجاتك الحيوية بملعقة واحدة.\n5. الدليل: توصية طبيب تغذية مع أكثر من 3000 مراجعة إيجابية.\n6. العرض: خصم 15% مع شحن مجاني وضمان استرداد أموال لمدة 30 يوماً.\n7. القالب: فيديو UGC تفاعلي مع لقطات مقارنة بصرية...",
          guideTitle: defaultMeta.tips[0].title,
          guideDescription: defaultMeta.tips[0].description,
          guidePoints: defaultMeta.tips[0].points,
          guideQuote: defaultMeta.tips[0].quote
        },
        {
          id: "ab_testing_plan",
          label: "خطة اختبار الزوايا الإعلانية ومجموعات المحتوى (قاعدة 1 زاوية = 5 إعلانات):",
          placeholder: "مثال لتطبيق الخطة الإبداعية ومقاييس الأداء:\n- زاوية (التزام أسهل) سنصمم لها 5 أشكال:\n  1. إعلان مشهد (درج مكملات مبعثر).\n  2. إعلان روتين صباحي (تحضير في 5 ثوانٍ).\n  3. إعلان ذنب (عدم الالتزام بالفيتامينات التقليدية).\n  4. إعلان مقارنة بصري (حبوب ضد بودرة).\n  5. إعلان شهادة عميلة حقيقية.\n- مقاييس النجاح للتحسين:\n  * Hook Rate المستهدف: >30%\n  * Hold Rate المستهدف: >20%...",
          guideTitle: defaultMeta.tips[1].title,
          guideDescription: defaultMeta.tips[1].description,
          guidePoints: defaultMeta.tips[1].points,
          guideQuote: defaultMeta.tips[1].quote
        }
      ];
    }
    setExercises(baselineExercises);
  };

  // Keep local state in sync with loaded answers
  useEffect(() => {
    const initializedAnswers: Record<string, string> = {};
    exercises.forEach((ex) => {
      initializedAnswers[ex.id] = answers[ex.id] || "";
    });
    setLocalAnswers(initializedAnswers);
  }, [answers, exercises]);

  // Save changes locally to state and auto-save in localStorage
  const handleInputChange = (fieldId: string, value: string) => {
    const updated = { ...localAnswers, [fieldId]: value };
    setLocalAnswers(updated);
    
    // Auto-save to localstorage temporarily
    localStorage.setItem(`temp_answers_${sectionId}`, JSON.stringify(updated));
  };

  // Perform a save action to the parent component (Supabase & localStorage permanent storage)
  const handleSaveAction = () => {
    onSave(sectionId, localAnswers);
    onToast("تم الحفظ والمزامنة السحابية بنجاح! ☁️", "success");
    
    // In-app visual notification effect on sidebar trigger (will pass status upward)
    const sidebarDot = document.getElementById(`sync-dot-${sectionId}`);
    if (sidebarDot) {
      sidebarDot.classList.add("scale-150", "bg-emerald-500");
      setTimeout(() => {
        sidebarDot.classList.remove("scale-150");
      }, 1000);
    }
  };

  // Perform reset action
  const handleResetAction = () => {
    onReset(sectionId, resetType);
    if (resetType === "all") {
      setLocalAnswers({});
      // Clear custom exercises
      localStorage.removeItem(`custom_exercises_${sectionId}`);
      loadDefaults();
      onToast("تمت إعادة ضبط الموديول ومسح البيانات نهائياً! 🗑️", "info");
    } else {
      // Keep custom exercises, clear fields
      const cleared: Record<string, string> = {};
      exercises.forEach((ex) => cleared[ex.id] = "");
      setLocalAnswers(cleared);
      onToast("تم إخلاء حقول الإدخال محلياً للقسم الحالي! 🧹", "info");
    }
    setShowConfirmReset(false);
  };

  // Partial export to structured Arabic TXT file
  const handlePartialExport = () => {
    let fileContent = `========================================\n`;
    fileContent += `   منصة الدراسة التفاعلية الذكية | مخرجات مخصصة\n`;
    fileContent += `========================================\n\n`;
    fileContent += `القسم: ${sectionTitle}\n`;
    fileContent += `تاريخ التصدير: ${new Date().toLocaleDateString("ar-EG")}\n`;
    fileContent += `----------------------------------------\n\n`;

    exercises.forEach((ex, idx) => {
      const answer = localAnswers[ex.id] || "بانتظار الإدخال";
      fileContent += `[${idx + 1}] السؤال: ${ex.label}\n`;
      fileContent += `    الإجابة: ${answer}\n`;
      fileContent += `----------------------------------------\n\n`;
    });

    const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `تقرير_${sectionTitle.replace(/\s+/g, "_")}.txt`;
    link.click();
    URL.revokeObjectURL(url);
    onToast("تم تصدير ملف التقرير النصي بنجاح! 📥", "success");
  };

  // Upload and parse custom lecture transcript using Gemini API
  const handleAiLectureAnalysis = async () => {
    if (!transcriptText.trim()) {
      onToast("برجاء إدخال نص المحاضرة للتمكن من تحليلها", "error");
      return;
    }

    setIsAnalyzing(true);
    try {
      const response = await fetch("/api/gemini/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: transcriptText,
          sectionId,
          sectionTitle: defaultMeta.title
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || "فشل الاتصال بالذكاء الاصطناعي");
      }

      const data = await response.json();
      
      // Save AI exercises to storage override
      const customPayload = {
        title: data.extractedTitle || defaultMeta.title,
        description: data.extractedDescription || defaultMeta.description,
        exercises: data.exercises || []
      };

      localStorage.setItem(`custom_exercises_${sectionId}`, JSON.stringify(customPayload));
      
      setExercises(data.exercises || []);
      setSectionTitle(customPayload.title);
      setSectionDesc(customPayload.description);
      
      // Reset local inputs to receive new parsed questions
      const cleared: Record<string, string> = {};
      data.exercises.forEach((ex: any) => {
        cleared[ex.id] = "";
      });
      setLocalAnswers(cleared);

      // Save floating assistant special tip
      if (data.floatingTip) {
        localStorage.setItem(`ai_floating_tip_${sectionId}`, data.floatingTip);
      }

      setShowUploadModal(false);
      setTranscriptText("");
      onToast("رائع! نجح الذكاء الاصطناعي في إعادة هيكلة الموديول بناءً على محاضرتك! 🧠✨", "success");
    } catch (err: any) {
      console.error(err);
      onToast(err.message || "حدث خطأ غير متوقع أثناء المعالجة الذكية.", "error");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Check if section is 100% completed
  const isSectionCompleted = exercises.length > 0 && exercises.every((ex) => localAnswers[ex.id]?.trim().length > 5);

  return (
    <div id={id || `section-view-${sectionId}`} className="space-y-8 animate-fade-in text-right">
      
      {/* Header controls bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 bg-white dark:bg-stone-900 p-5 rounded-3xl border border-stone-100 dark:border-stone-800 shadow-sm">
        <button
          onClick={onBackToDashboard}
          className="flex items-center gap-2 text-stone-600 dark:text-stone-400 hover:text-brand-primary dark:hover:text-brand-secondary text-sm font-semibold cursor-pointer py-1.5 px-3 hover:bg-stone-50 dark:hover:bg-stone-800 rounded-xl transition-all"
        >
          <ArrowRight className="w-4 h-4" />
          <span>العودة للرئيسية</span>
        </button>

        {/* Floating actions menu */}
        <div className="flex flex-wrap items-center justify-center gap-2.5">
          {/* AI Customization Button */}
          <button
            onClick={() => setShowUploadModal(true)}
            className="px-4 py-2 bg-brand-primary/10 hover:bg-brand-primary/20 dark:bg-brand-secondary/10 dark:hover:bg-brand-secondary/20 text-brand-primary dark:text-brand-secondary rounded-xl font-bold text-xs flex items-center gap-1.5 transition-all cursor-pointer border border-brand-primary/20"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>تخصيص بمحاضرة خارجية (AI)</span>
          </button>

          {/* Export to TXT */}
          <button
            onClick={handlePartialExport}
            className="px-4 py-2 bg-stone-100 dark:bg-stone-800 hover:bg-stone-200 dark:hover:bg-stone-700 text-stone-800 dark:text-white rounded-xl font-semibold text-xs flex items-center gap-1.5 transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>تصدير هذا القسم</span>
          </button>

          {/* Reset button */}
          <button
            onClick={() => {
              setResetType("local");
              setShowConfirmReset(true);
            }}
            className="px-4 py-2 bg-rose-50 dark:bg-rose-950/20 hover:bg-rose-100 dark:hover:bg-rose-950/40 text-rose-600 dark:text-rose-400 rounded-xl font-semibold text-xs flex items-center gap-1.5 transition-all cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>إعادة ضبط</span>
          </button>

          {/* Core manual Save */}
          <button
            onClick={handleSaveAction}
            className="px-5 py-2 bg-brand-primary hover:bg-brand-primary/95 text-white dark:bg-brand-secondary dark:text-black dark:hover:bg-brand-secondary/90 rounded-xl font-bold text-xs flex items-center gap-1.5 shadow-md hover:shadow-lg transition-all duration-200 cursor-pointer"
          >
            <Save className="w-3.5 h-3.5" />
            <span>حفظ ومزامنة سحابية</span>
          </button>
        </div>
      </div>

      {/* Hero Banner details of Section */}
      <div className="bg-stone-50 dark:bg-stone-950/40 p-8 rounded-3xl border border-stone-100 dark:border-stone-800 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-brand-primary/5 rounded-full blur-2xl"></div>
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-1.5 bg-brand-primary/10 dark:bg-brand-secondary/10 px-3.5 py-1 rounded-full text-brand-primary dark:text-brand-secondary text-xs font-bold">
              <BookOpen className="w-3.5 h-3.5" />
              <span>موديول العمل الذكي</span>
            </div>
            <h1 className="text-2xl font-black text-stone-900 dark:text-white">{sectionTitle}</h1>
            <p className="text-xs text-stone-500 dark:text-stone-400 max-w-2xl leading-relaxed">{sectionDesc}</p>
          </div>

          {/* Completeness badge */}
          <div>
            {isSectionCompleted ? (
              <div className="flex items-center gap-2 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900 p-4 rounded-2xl text-emerald-700 dark:text-emerald-400">
                <CheckCircle className="w-5 h-5 shrink-0" />
                <div>
                  <h4 className="font-extrabold text-xs">عمل متكامل ومثالي!</h4>
                  <p className="text-[10px] opacity-80">تم ملء جميع الحقول بنجاح وبانتظار تقييمك النهائي.</p>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-2 bg-amber-50/60 dark:bg-amber-950/10 border border-amber-200/40 dark:border-amber-900/30 p-4 rounded-2xl text-amber-700 dark:text-amber-500">
                <AlertTriangle className="w-5 h-5 shrink-0 animate-pulse" />
                <div>
                  <h4 className="font-extrabold text-xs">بانتظار الإدخال والتحليل</h4>
                  <p className="text-[10px] opacity-80">يرجى قراءة التوجيهات وملء المساحات المطلوبة بالأسفل.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Main Exercises List Container */}
      <div className="space-y-8">
        {exercises.map((ex, index) => {
          const isAnswered = (localAnswers[ex.id] || "").trim().length > 5;
          
          return (
            <motion.div
              key={ex.id}
              whileHover={{ scale: 1.005 }}
              className={`bg-white dark:bg-stone-900 p-6 sm:p-8 rounded-3xl border-2 transition-all duration-300 relative ${
                isAnswered
                  ? "border-brand-secondary/70 bg-brand-secondary/[0.01]"
                  : "border-stone-100 dark:border-stone-800 glow-secondary-hover"
              }`}
            >
              {/* Header inside the Card */}
              <div className="flex items-center justify-between mb-4 border-b border-stone-50 dark:border-stone-800 pb-3">
                <div className="flex items-center gap-2.5">
                  <span className="w-7 h-7 bg-brand-primary text-white dark:bg-brand-secondary dark:text-black font-mono font-bold text-xs rounded-full flex items-center justify-center">
                    {index + 1}
                  </span>
                  <label htmlFor={ex.id} className="font-bold text-stone-900 dark:text-white text-sm sm:text-base cursor-pointer">
                    {ex.label}
                  </label>
                </div>

                {/* Micro status state indicator */}
                <div>
                  {isAnswered ? (
                    <span className="text-[10px] text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/40 px-2.5 py-1 rounded-full font-bold flex items-center gap-1 animate-fade-in">
                      <CheckCircle className="w-3.5 h-3.5" />
                      <span>تم التسجيل</span>
                    </span>
                  ) : (
                    <span className="text-[9px] text-stone-400 dark:text-stone-500 bg-stone-50 dark:bg-stone-950 px-2 py-1 rounded-full font-light">
                      بانتظار الإدخال
                    </span>
                  )}
                </div>
              </div>

              {/* Input Area */}
              <div className="relative">
                <textarea
                  id={ex.id}
                  rows={4}
                  value={localAnswers[ex.id] || ""}
                  onChange={(e) => handleInputChange(ex.id, e.target.value)}
                  placeholder={ex.placeholder}
                  className="w-full p-4 text-xs sm:text-sm bg-stone-50 dark:bg-stone-950 border border-stone-200/60 dark:border-stone-800 rounded-2xl outline-none focus:ring-2 focus:ring-brand-secondary focus:border-transparent transition-all duration-300 resize-none leading-relaxed text-stone-800 dark:text-stone-100"
                />
              </div>

              {/* Accordion Smart Guide inside the Card */}
              <SmartGuide
                title={ex.guideTitle}
                description={ex.guideDescription}
                points={ex.guidePoints}
                quote={ex.guideQuote}
              />
            </motion.div>
          );
        })}
      </div>

      {/* Confirmation Reset Modal */}
      {showConfirmReset && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-stone-900 p-6 rounded-3xl border border-stone-200 dark:border-stone-800 shadow-2xl max-w-md w-full text-right space-y-4"
          >
            <div className="flex items-center gap-3 text-rose-600 dark:text-rose-400">
              <AlertTriangle className="w-6 h-6 shrink-0" />
              <h3 className="font-bold text-lg">تأكيد إعادة ضبط القسم:</h3>
            </div>
            
            <p className="text-xs text-stone-500 dark:text-stone-400 leading-relaxed">
              تحذير: ستقوم هذه الخطوة بمسح المدخلات الخاصة بهذا الموديول بالكامل. يرجى اختيار مستوى المسح:
            </p>

            <div className="space-y-2">
              <label className="flex items-center gap-3 p-3 bg-stone-50 dark:bg-stone-950 rounded-2xl border border-stone-100 dark:border-stone-800 cursor-pointer">
                <input
                  type="radio"
                  name="reset-choice"
                  checked={resetType === "local"}
                  onChange={() => setResetType("local")}
                  className="text-brand-primary focus:ring-brand-primary"
                />
                <div className="text-right">
                  <p className="text-xs font-bold text-stone-800 dark:text-white">إفراغ حقول الإدخال محلياً فقط</p>
                  <p className="text-[10px] text-stone-400">ستبقى الهيكلية والبيانات المخزنة سحابياً كما هي حتى تضغط حفظ.</p>
                </div>
              </label>

              <label className="flex items-center gap-3 p-3 bg-rose-50/40 dark:bg-rose-950/10 rounded-2xl border border-rose-100/40 dark:border-rose-900/20 cursor-pointer">
                <input
                  type="radio"
                  name="reset-choice"
                  checked={resetType === "all"}
                  onChange={() => setResetType("all")}
                  className="text-rose-600 focus:ring-rose-600"
                />
                <div className="text-right">
                  <p className="text-xs font-bold text-rose-700 dark:text-rose-400">مسح كلي نهائي (شامل البيانات والسحابة)</p>
                  <p className="text-[10px] text-stone-400">ستعود الهيكلية لوضعها الافتراضي الأولي ويمسح ملفك تماماً.</p>
                </div>
              </label>
            </div>

            <div className="flex items-center justify-end gap-3 pt-3">
              <button
                onClick={() => setShowConfirmReset(false)}
                className="px-4 py-2 bg-stone-100 dark:bg-stone-800 text-stone-700 dark:text-white text-xs font-bold rounded-xl cursor-pointer"
              >
                تراجع وإلغاء
              </button>
              <button
                onClick={handleResetAction}
                className="px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold rounded-xl flex items-center gap-1 cursor-pointer"
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span>تنفيذ المسح</span>
              </button>
            </div>
          </motion.div>
        </div>
      )}

      {/* AI Lecture Upload Modal */}
      {showUploadModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-stone-900 p-6 rounded-3xl border border-stone-200 dark:border-stone-800 shadow-2xl max-w-xl w-full text-right space-y-4"
          >
            <div className="flex items-center gap-3 text-brand-primary dark:text-brand-secondary">
              <Sparkles className="w-5 h-5 shrink-0" />
              <h3 className="font-bold text-lg">تخصيص الموديول بمحاضرتك التعليمية (AI):</h3>
            </div>
            
            <p className="text-xs text-stone-500 dark:text-stone-400 leading-relaxed">
              قم بلصق محتوى المحاضرة أو نص تفريغ الفيديو/الصوت بالكامل في المساحة أدناه. سيقوم المساعد الذكي <span className="font-bold text-brand-primary dark:text-brand-secondary">Gemini 3.5 Flash</span> بقراءة المحتوى وتحديث حقول العمل مع توليد دليل توجيهات تفصيلي مخصص للدرس فوراً!
            </p>

            <div className="space-y-2">
              <textarea
                rows={6}
                value={transcriptText}
                onChange={(e) => setTranscriptText(e.target.value)}
                placeholder="ألصق هنا النص التفريغي للمحاضرة أو الدرس المكتوب..."
                className="w-full p-4 text-xs bg-stone-50 dark:bg-stone-950 border border-stone-200 dark:border-stone-800 rounded-2xl outline-none focus:ring-2 focus:ring-brand-secondary resize-none"
              />
            </div>

            <div className="flex items-center justify-between pt-3 border-t border-stone-100 dark:border-stone-800">
              <span className="text-[10px] text-stone-400">
                ملاحظة: يتطلب هذا الإجراء تهيئة مفتاح الـ API للذكاء الاصطناعي بنجاح.
              </span>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => {
                    setShowUploadModal(false);
                    setTranscriptText("");
                  }}
                  className="px-4 py-2 bg-stone-100 dark:bg-stone-800 text-stone-700 dark:text-white text-xs font-bold rounded-xl cursor-pointer"
                  disabled={isAnalyzing}
                >
                  إلغاء
                </button>
                <button
                  onClick={handleAiLectureAnalysis}
                  className="px-5 py-2 bg-brand-primary hover:bg-brand-primary/95 text-white dark:bg-brand-secondary dark:text-black dark:hover:bg-brand-secondary/90 text-xs font-bold rounded-xl flex items-center gap-2 shadow-md cursor-pointer"
                  disabled={isAnalyzing}
                >
                  {isAnalyzing ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      <span>جاري المعالجة والتحليل...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>تحليل وصياغة التمارين</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}

    </div>
  );
};
